#!/usr/bin/env python3

import pyrealsense2 as rs
import numpy as np
import cv2
import click


@click.command()
@click.option(
    '--width',
    default=848,
    required=False,
    type=int,
    help='Recording width.'
)
@click.option(
    '--height',
    default=480,
    required=False,
    type=int,
    help='Recording height.'
)
@click.option(
    '--fps',
    default=30,
    required=False,
    type=int,
    help='Recording FPS.'
)
def rsstream(width, height, fps):

    # Record at most one minute of data.
    # MAX_FRAMES = FPS * 60
    MAX_FRAMES = None

    DIMS = (width, height)

    # RealSense configuration.
    config = rs.config()
    config.enable_stream(rs.stream.depth, DIMS[0], DIMS[1], rs.format.z16, fps)
    config.enable_stream(rs.stream.color, DIMS[0], DIMS[1], rs.format.bgr8, fps)

    # Pipeline for frame capture.
    pipeline = rs.pipeline()
    pipeline.start(config)

    while True:
        
        # Wait for frames.
        frames = pipeline.wait_for_frames()
        depth_frame = frames.get_depth_frame()
        color_frame = frames.get_color_frame()
        if not depth_frame or not color_frame: continue

        depth_data = np.asanyarray(depth_frame.as_frame().get_data())
        color_data = np.asanyarray(color_frame.as_frame().get_data())
            
        depth_colormap = cv2.applyColorMap(
            cv2.convertScaleAbs(depth_data, alpha=0.03), 
            cv2.COLORMAP_JET
        )
        cv2.imshow('depth', depth_colormap)
        cv2.imshow('color', color_data)
        cv2.waitKey(1)


if __name__ == '__main__':
    rsstream()
