#!/usr/bin/env python3

import numpy as np
import cv2
import click
import h5py


@click.command()
@click.option(
    '--depth-filename',
    required=True,
    help='Filename for depth video (should end in .h5).'
)
@click.option(
    '--color-filename',
    required=True,
    help='Filename for color video (should end in .avi).'
)
def rsplayback(depth_filename, color_filename):
    """
    Play back captured depth and color video files.
    """

    if not depth_filename.endswith('.h5') or not color_filename.endswith('.avi'):
        raise Exception('Filename extensions are incorrect.')

    # Stream for the color video.
    color_cap = cv2.VideoCapture(color_filename)

    # Load the depth stream dataset.
    depth_f = h5py.File(depth_filename, 'r')
    depth_data = depth_f['depth']

    # Get dimensions (W,H) and number of frames N.
    N, H, W = depth_data.shape

    for i in range(N):
        
        # Obtain and display the color frame.
        ret, frame_color = color_cap.read()
        if ret: cv2.imshow('color', frame_color)

        # Obtain and display the depth frame.
        frame_depth = depth_data[i,:,:]
        depth_colormap = cv2.applyColorMap(
            cv2.convertScaleAbs(frame_depth, alpha=0.03), 
            cv2.COLORMAP_JET
        )
        cv2.imshow('depth', depth_colormap)
        cv2.waitKey(1)



if __name__ == '__main__':
    rsplayback()
